# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Curie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Curie
  pod 'Auth0', '~> 1.13'
  pod 'SDLoopingVideoView'

  target 'CurieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
